### ISSUE TITLE
Sindri Borks on File Read

### ISSUE THREAD

**Issue by pbitzer** [project-mjolnir/sindri#1]
When one of the log files has a bad line, Sindri will bork and the site no longer updates. This can happen when Brokkr (the logger) fails in the middle of file write. The CSV-ness is lost.

**Comment by CAM-Gerlach** [comment]
As opposed to Sindri, in which I don't yet have particularly rigorous error handling implemented, I tried to be very "safe" with the code in Brokkr to minimize write time, handle errors gracefully and suppress interrupts while the file is actually being written to; I'm curious as to what circumstances this can happen. In any case, the easiest solution should be to just set `error_bad_lines=False` in the call to `pd.read_csv`.

**Comment by pbitzer** [comment]
> In any case, the easiest solution should be to just set `error_bad_lines=False` in the call to `pd.read_csv`.

Yep, that's what I got.

I saw the website not updating. Upon further inspection, it seemed to fail when (I assume) the Brokkr failed (for whatever reason, including a force kill) in the middle of a line write. When restarting Brokkr, it would start writing on the same line. This led to a line that is longer than expected.

**Comment by CAM-Gerlach** [comment]
> I saw the website not updating. Upon further inspection, it seemed to fail when (I assume) the Brokkr failed (for whatever reason, including a force kill) in the middle of a line write. When restarting Brokkr, it would start writing on the same line. This led to a line that is longer than expected.

Ah, thanks for the details. 

Hmm, I thought that would be very unlikely, because according to my logged telemetry, the entire CSV output step takes less than 4 ms to run, and the data is written in a single call within that function, with write buffering enabled, I have a signal handler registered, and the actual write itself is performed (AFAIK) in the C code, whereas interrupts don't get served until the function returns.

In any case, I can include a check in the CSV outputstep that checks if the last char in the file is a newline, and adds one if not.
