### ISSUE TITLE
Build failure on empty file

### ISSUE THREAD

**Issue by pbitzer** [project-mjolnir/sindri#19]
If something goes sideways with `brokkr` or the disk is full, the log file `sindru` reads can be empty. `Sindri` fails to build in these cases, with the ultimate error coming from Pandas: `pandas.errors.EmptyDataError: No columns to parse from file`

We need to sidestep empty files, in a similar manner as the fix for #1 I imagine. 

Edge case. Low priority.

**Comment by CAM-Gerlach** [comment]
Good catch. This one instance may be edge case, but simple to fix and will help recover from a whole class of errors—we can just catch and log any unhanded errors reading a file and skip it instead. Since the `read_csv()` call is currently inside a generator expression feeding it directly to `pd.concat`, we can wrap that in a function with the error handling and then call that in the generator. I can test and push a fix to the current 0.3.x stable branch.
